In [1]:
import torch
import pandas as pd

In [ ]:

df = pd.read_csv('../data/student_scores.csv')  

inputs = torch.tensor(df['hours'].values, dtype=torch.float32).view(-1, 1)
targets = torch.tensor(df['marks'].values, dtype=torch.float32).view(-1, 1)


[inputs[:10], targets[:10]]

[tensor([[ 5.1200],
         [11.4600],
         [ 9.0500],
         [ 7.5900],
         [ 2.7200],
         [ 2.7200],
         [ 1.6400],
         [10.5300],
         [ 7.6100],
         [ 8.7900]]),
 tensor([[44.4100],
         [90.7200],
         [78.8400],
         [67.5300],
         [25.8900],
         [28.4900],
         [18.1000],
         [91.7800],
         [64.3500],
         [66.4000]])]

In [3]:
w = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(w)
print(b)

tensor([[0.6349]], requires_grad=True)
tensor([0.6115], requires_grad=True)


In [ ]:
# Define the Linear Regression model
def model(x):
    return x @ w + b

In [5]:
preds = model(inputs)

preds[:10]

tensor([[3.8624],
        [7.8879],
        [6.3577],
        [5.4307],
        [2.3385],
        [2.3385],
        [1.6528],
        [7.2974],
        [5.4434],
        [6.1926]], grad_fn=<SliceBackward0>)

In [6]:
print(targets[:10])

tensor([[44.4100],
        [90.7200],
        [78.8400],
        [67.5300],
        [25.8900],
        [28.4900],
        [18.1000],
        [91.7800],
        [64.3500],
        [66.4000]])


In [ ]:
# Mean Squared Error (MSE) loss function
def mse(preds, targets):
    diff = preds - targets
    return torch.sum(diff * diff) / diff.numel()

loss = mse(preds, targets)
print(loss)

tensor(3146.9197, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward()

In [9]:
print(w)
print(w.grad)

tensor([[0.6349]], requires_grad=True)
tensor([[-799.6608]])


In [10]:
w.grad.zero_()
b.grad.zero_()

tensor([0.])

In [ ]:
# Update the weights using gradient descent
with torch.no_grad():
    w -= 1e-5 * w.grad
    b -= 1e-5 * b.grad
    w.grad.zero_()
    b.grad.zero_()

In [12]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(3146.9197, grad_fn=<DivBackward0>)


In [ ]:
#  Train the model for 1000 iterations
for i in range(1000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [301]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(23.5619, grad_fn=<DivBackward0>)


In [302]:
preds[:10]

tensor([[44.1143],
        [97.0927],
        [76.9542],
        [64.7541],
        [24.0593],
        [24.0593],
        [15.0346],
        [89.3214],
        [64.9213],
        [74.7816]], grad_fn=<SliceBackward0>)

In [16]:
targets[:10]

tensor([[44.4100],
        [90.7200],
        [78.8400],
        [67.5300],
        [25.8900],
        [28.4900],
        [18.1000],
        [91.7800],
        [64.3500],
        [66.4000]])