In [2]:
import pandas as pd

import torch
from torch.utils.data import TensorDataset,  DataLoader
import torch.nn as nn
import torch.nn.functional as F



In [3]:
df = pd.read_csv('../data/student_scores.csv')

inputs = torch.tensor(df['hours'].values, dtype=torch.float32).view(-1, 1)
targets = torch.tensor(df['marks'].values, dtype=torch.float32).view(-1, 1)

print(inputs[:10], targets[:10])

tensor([[ 5.1200],
        [11.4600],
        [ 9.0500],
        [ 7.5900],
        [ 2.7200],
        [ 2.7200],
        [ 1.6400],
        [10.5300],
        [ 7.6100],
        [ 8.7900]]) tensor([[44.4100],
        [90.7200],
        [78.8400],
        [67.5300],
        [25.8900],
        [28.4900],
        [18.1000],
        [91.7800],
        [64.3500],
        [66.4000]])


In [ ]:
# Create a TensorDataset from the input and target tensors
train_ds = TensorDataset(inputs, targets)

train_ds[:10]

(tensor([[ 5.1200],
         [11.4600],
         [ 9.0500],
         [ 7.5900],
         [ 2.7200],
         [ 2.7200],
         [ 1.6400],
         [10.5300],
         [ 7.6100],
         [ 8.7900]]),
 tensor([[44.4100],
         [90.7200],
         [78.8400],
         [67.5300],
         [25.8900],
         [28.4900],
         [18.1000],
         [91.7800],
         [64.3500],
         [66.4000]]))

In [ ]:
# Create a DataLoader for batching and shuffling the training data
batch_size = 32
train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True)

In [ ]:
# Initialize the model, loss function, and optimizer
model = nn.Linear(1, 1)
loss_fn = F.mse_loss
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
# Train the model using mini-batch gradient descent
epochs = 1000
for epoch in range(epochs):
    for xb, yb in train_dl:
        pred = model(xb)
        loss = loss_fn(pred, yb) 
        
        loss.backward()
        optimizer.zero_grad()
        optimizer.step()
        
    if (epoch+1) % 100 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 100, Loss: 2211.955078125
Epoch 200, Loss: 2517.49951171875
Epoch 300, Loss: 2880.910888671875
Epoch 400, Loss: 1566.5877685546875
Epoch 500, Loss: 2959.923828125
Epoch 600, Loss: 3920.9873046875
Epoch 700, Loss: 4147.8671875
Epoch 800, Loss: 2669.5390625
Epoch 900, Loss: 3328.4677734375
Epoch 1000, Loss: 5582.5830078125


In [8]:
preds = model(inputs)
preds[:10]

tensor([[2.3490],
        [5.2752],
        [4.1629],
        [3.4890],
        [1.2413],
        [1.2413],
        [0.7429],
        [4.8459],
        [3.4982],
        [4.0429]], grad_fn=<SliceBackward0>)

In [9]:
targets[:10]

tensor([[44.4100],
        [90.7200],
        [78.8400],
        [67.5300],
        [25.8900],
        [28.4900],
        [18.1000],
        [91.7800],
        [64.3500],
        [66.4000]])