In [1]:
import pandas as pd

import torch
from torch.utils.data import TensorDataset,  DataLoader
import torch.nn as nn
import torch.nn.functional as F



In [2]:
df = pd.read_csv('data/student_scores.csv')

inputs = torch.tensor(df['hours'].values, dtype=torch.float32).view(-1, 1)
targets = torch.tensor(df['marks'].values, dtype=torch.float32).view(-1, 1)

print(inputs[:10], targets[:10])

tensor([[ 5.1200],
        [11.4600],
        [ 9.0500],
        [ 7.5900],
        [ 2.7200],
        [ 2.7200],
        [ 1.6400],
        [10.5300],
        [ 7.6100],
        [ 8.7900]]) tensor([[44.4100],
        [90.7200],
        [78.8400],
        [67.5300],
        [25.8900],
        [28.4900],
        [18.1000],
        [91.7800],
        [64.3500],
        [66.4000]])


In [3]:
train_ds = TensorDataset(inputs, targets)

train_ds[:10]

(tensor([[ 5.1200],
         [11.4600],
         [ 9.0500],
         [ 7.5900],
         [ 2.7200],
         [ 2.7200],
         [ 1.6400],
         [10.5300],
         [ 7.6100],
         [ 8.7900]]),
 tensor([[44.4100],
         [90.7200],
         [78.8400],
         [67.5300],
         [25.8900],
         [28.4900],
         [18.1000],
         [91.7800],
         [64.3500],
         [66.4000]]))

In [4]:
batch_size = 32
train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True)

In [5]:
model = nn.Linear(1, 1)
loss_fn = F.mse_loss
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [12]:
epochs = 10000
for epoch in range(epochs):
    for xb, yb in train_dl:
        pred = model(xb)
        loss = loss_fn(pred, yb) 
        
        loss.backward()
        optimizer.zero_grad()
        optimizer.step()
        
    if (epoch+1) % 1000 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1000, Loss: 4251.201171875
Epoch 2000, Loss: 2597.06201171875
Epoch 3000, Loss: 2683.81298828125
Epoch 4000, Loss: 3656.96875
Epoch 5000, Loss: 1600.524658203125
Epoch 6000, Loss: 2496.2109375
Epoch 7000, Loss: 3227.865478515625
Epoch 8000, Loss: 4177.89013671875
Epoch 9000, Loss: 3785.482421875
Epoch 10000, Loss: 2086.938720703125


In [10]:
preds = model(inputs)
preds[:10]

tensor([[3.6968],
        [7.6199],
        [6.1286],
        [5.2252],
        [2.2117],
        [2.2117],
        [1.5435],
        [7.0444],
        [5.2376],
        [5.9678]], grad_fn=<SliceBackward0>)

In [11]:
targets[:10]

tensor([[44.4100],
        [90.7200],
        [78.8400],
        [67.5300],
        [25.8900],
        [28.4900],
        [18.1000],
        [91.7800],
        [64.3500],
        [66.4000]])