In [175]:
import pandas as pd

import torch
from torch.utils.data import TensorDataset,  DataLoader
import torch.nn as nn
import torch.nn.functional as F



In [176]:
torch.manual_seed(42)

In [177]:
df = pd.read_csv('../data/student_scores.csv')

inputs = torch.tensor(df['hours'].values, dtype=torch.float32).view(-1, 1)
targets = torch.tensor(df['marks'].values, dtype=torch.float32).view(-1, 1)

print(inputs[:10], targets[:10])

tensor([[ 5.1200],
        [11.4600],
        [ 9.0500],
        [ 7.5900],
        [ 2.7200],
        [ 2.7200],
        [ 1.6400],
        [10.5300],
        [ 7.6100],
        [ 8.7900]]) tensor([[44.4100],
        [90.7200],
        [78.8400],
        [67.5300],
        [25.8900],
        [28.4900],
        [18.1000],
        [91.7800],
        [64.3500],
        [66.4000]])


In [178]:
# Create a TensorDataset from the input and target tensors
train_ds = TensorDataset(inputs, targets)

train_ds[:10]

(tensor([[ 5.1200],
         [11.4600],
         [ 9.0500],
         [ 7.5900],
         [ 2.7200],
         [ 2.7200],
         [ 1.6400],
         [10.5300],
         [ 7.6100],
         [ 8.7900]]),
 tensor([[44.4100],
         [90.7200],
         [78.8400],
         [67.5300],
         [25.8900],
         [28.4900],
         [18.1000],
         [91.7800],
         [64.3500],
         [66.4000]]))

In [179]:
# Create a DataLoader for batching and shuffling the training data
batch_size = 32
train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True)

In [180]:
# Initialize the model, loss function, and optimizer
model = nn.Linear(1, 1)
loss_fn = F.mse_loss
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [181]:
# Train the model using mini-batch gradient descent
epochs = 1000
for epoch in range(epochs):
    for xb, yb in train_dl:
        pred = model(xb)
        loss = loss_fn(pred, yb) 
        
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        
    if (epoch+1) % 100 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 100, Loss: 36.73912811279297
Epoch 200, Loss: 28.479711532592773
Epoch 300, Loss: 20.58246612548828
Epoch 400, Loss: 14.663695335388184
Epoch 500, Loss: 42.10380554199219
Epoch 600, Loss: 8.425576210021973
Epoch 700, Loss: 24.098299026489258
Epoch 800, Loss: 36.52971267700195
Epoch 900, Loss: 12.385515213012695
Epoch 1000, Loss: 9.639121055603027


In [182]:
preds = model(inputs)
preds[:10]

tensor([[44.2468],
        [96.9257],
        [76.9011],
        [64.7700],
        [24.3053],
        [24.3053],
        [15.3316],
        [89.1984],
        [64.9362],
        [74.7408]], grad_fn=<SliceBackward0>)

In [183]:
targets[:10]

tensor([[44.4100],
        [90.7200],
        [78.8400],
        [67.5300],
        [25.8900],
        [28.4900],
        [18.1000],
        [91.7800],
        [64.3500],
        [66.4000]])